{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "agent.serviceAccountName" . }}
  labels:
    app.kubernetes.io/component: grafana-agent
{{ include "agent.labels" . | indent 4 }}
{{- end -}}

